language: python
python:
  - "2.7"
install:
  - "sudo apt-get update"
  - "sudo apt-get install python-all-dev pandoc"
  - "pandoc -f markdown -t rst -o README.rst README.md"
  - "pip install tox --use-mirrors"
script: tox
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
